site_name: THUAC RFC
nav:
- 简介: index.md
- 概览: abstract.md
- 游戏: game.md
- 控制器: controller.md
- 裁判: judger.md
- 播放器: player.md
- SDK(AI): SDK(AI).md
- 网站: website.md
- 网站后端-测评端: backend2judger.md
- 网站前端-房间系统: frontend2room.md
- 房间系统-播放器: room2player.md
- 网站前端-概览: website_frontend.md
- 网站前端-用户系统: website-frontend-user.md
- 网站前端-小组系统: website-frontend-group.md

theme: readthedocs
