site_name: THUAC RFC
nav:
- 简介: index.md
- 概览: abstract.md
- 游戏: game.md
- 控制器: controller.md
- 裁判: judger.md
- 播放器: player.md
- SDK(AI): SDK(AI).md
- 网站: website.md
- 网站后端-测评端: backend2judger.md


theme: readthedocs
